# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.hospital1.example.com:
  P874LG:
  P09Q6Y:
  P60CC5:
  P30KEH:
  P51VDL:

networks:
  ehrnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  orderer0.hospital1.example.com:
    container_name: orderer0.hospital1.example.com
    extends:
      file: docker/compose-base.yaml
      service: orderer0.hospital1.example.com
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.100

  P874LG:
    container_name: P874LG
    extends:
      file: docker/compose-base.yaml
      service: P874LG
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.10

  P09Q6Y:
    container_name: P09Q6Y
    extends:
      file: docker/compose-base.yaml
      service: P09Q6Y
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.20

  P60CC5:
    container_name: P60CC5
    extends:
      file: docker/compose-base.yaml
      service: P60CC5
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.30

  P30KEH:
    container_name: P30KEH
    extends:
      file: docker/compose-base.yaml
      service: P30KEH
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.40

  P51VDL:
    container_name: P51VDL
    extends:
      file: docker/compose-base.yaml
      service: P51VDL
    networks:
      ehrnetwork:
        ipv4_address: 172.20.0.50

  cli0:
    container_name: cli0
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli0
      - CORE_PEER_ADDRESS=P874LG:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.example.com/peers/P874LG/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.example.com/peers/P874LG/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.example.com/peers/P874LG/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.example.com/users/Admin@hospital1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - ehrnetwork
    depends_on:
      - orderer0.hospital1.example.com
      - P874LG
      - P09Q6Y
      - P60CC5
      - P30KEH
      - P51VDL
