# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.hospital1.example.com:
    container_name: orderer0.hospital1.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Hospital1MSP
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.hospital1.example.com:9440
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/orderer0.hospital1.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/orderer0.hospital1.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer0.hospital1.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  P874LG:
    container_name: P874LG
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=P874LG
      - CORE_PEER_ADDRESS=P874LG:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=P874LG:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=P09Q6Y:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_OPERATIONS_LISTENADDRESS=P874LG:9441
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P874LG/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P874LG/tls:/etc/hyperledger/fabric/tls
      - P874LG:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  P09Q6Y:
    container_name: P09Q6Y
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=P09Q6Y
      - CORE_PEER_ADDRESS=P09Q6Y:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=P09Q6Y:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=P874LG:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_OPERATIONS_LISTENADDRESS=P09Q6Y:9442
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P09Q6Y/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P09Q6Y/tls:/etc/hyperledger/fabric/tls
      - P09Q6Y:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  P60CC5:
    container_name: P60CC5
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=P60CC5
      - CORE_PEER_ADDRESS=P60CC5:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=P60CC5:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=P874LG:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_OPERATIONS_LISTENADDRESS=P60CC5:9442
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P60CC5/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P60CC5/tls:/etc/hyperledger/fabric/tls
      - P60CC5:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  P30KEH:
    container_name: P30KEH
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=P30KEH
      - CORE_PEER_ADDRESS=P30KEH:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=P30KEH:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=P874LG:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_OPERATIONS_LISTENADDRESS=P30KEH:9442
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P30KEH/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P30KEH/tls:/etc/hyperledger/fabric/tls
      - P30KEH:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  P51VDL:
    container_name: P51VDL
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=P51VDL
      - CORE_PEER_ADDRESS=P51VDL:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=P51VDL:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=P874LG:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_OPERATIONS_LISTENADDRESS=P51VDL:9442
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P51VDL/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hospital1.example.com/peers/P51VDL/tls:/etc/hyperledger/fabric/tls
      - P51VDL:/var/hyperledger/production

    ports:
      - 11051:7051
      - 11053:7053